@baseUrl = https://localhost:5001/api

###

POST {{baseUrl}}/telegrambot HTTP/1.1
content-type: application/json

{
    "activate": true,
    "passwd": "zzzzz"
}

###

GET {{baseUrl}}/telegrambot HTTP/1.1
content-type: application/json

###

GET {{baseUrl}}/telegrambot/quantity HTTP/1.1
content-type: application/json

###

GET {{baseUrl}}/statistics HTTP/1.1
content-type: application/json