POST  HTTP/1.1
header name: header value
###

POST http://localhost:5000/telegrambot/ HTTP/1.1
content-type: application/json

{
    "activate": true
}
###

POST https://bottelegramrcolzani.herokuapp.com/telegrambot HTTP/1.1
content-type: application/json

{
    "activate": true
}