version: "3.8"

volumes:
  TelegramBotDb:

networks:
  TelegramBotNET:

services:
  telegrambot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegrambot
    networks:
      - TelegramBotNET
    ports:
      - 5000:80

