version: "3.8"

volumes:
  TelegramBotDb:

networks:
  TelegramBotNET:

services:
  mysql:
    image: "mysql:5.7"
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - TelegramBotDb:/var/lib/mysql
    networks:
      - TelegramBotNET
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_ROOT_HOST=%
      - bind-address:0.0.0.0

  telegrambot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegrambot
    networks:
      - TelegramBotNET
    ports:
      - 5000:80
    environment:
      - DBHOST=mysql
    depends_on:
      - mysql
